import { ChildProcess, spawn } from 'child_process'
import * as path from 'path'
import * as fs from 'fs'
import { app } from 'electron'
import { getBrandConfig } from './brand-config'

let openClawProcess: ChildProcess | null = null
const OPENCLAW_PORT = 3007

function getOpenClawDir(): string {
  const devPath = path.join(__dirname, '..', 'openclaw')
  if (fs.existsSync(devPath)) return devPath
  return path.join(process.resourcesPath || '', 'openclaw')
}

function getNodePath(): string {
  // Bundled Node.js (production)
  const platform = process.platform
  const nodeBin = platform === 'win32' ? 'node.exe' : 'bin/node'
  const bundledPaths = [
    path.join(process.resourcesPath || '', 'node', nodeBin),
    path.join(process.resourcesPath || '', 'node', platform === 'win32' ? 'node.exe' : 'node'),
  ]
  for (const p of bundledPaths) {
    if (fs.existsSync(p)) return p
  }
  // Fallback to system node
  return 'node'
}

function getDataDir(): string {
  const dir = path.join(app.getPath('userData'), 'openclaw-data')
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
  return dir
}

/**
 * First-run initialization: write OpenClaw config with brand API URL
 * so OpenClaw uses YourPro backend as its model provider.
 */
export function ensureOpenClawConfig() {
  const dataDir = getDataDir()
  const brand = getBrandConfig()

  // Write a .env or config that OpenClaw reads for API base URL
  const envFile = path.join(dataDir, '.env')
  const envContent = [
    `# Auto-generated by YourClaw`,
    `OPENAI_API_BASE=${brand.siteUrl}/v1`,
    `OPENAI_API_KEY=yourclaw-jwt-placeholder`,
    `DATA_DIR=${dataDir}`,
    `PORT=${OPENCLAW_PORT}`,
  ].join('\n')

  // Only write if different or missing
  try {
    const existing = fs.existsSync(envFile) ? fs.readFileSync(envFile, 'utf-8') : ''
    if (!existing.includes(brand.siteUrl)) {
      fs.writeFileSync(envFile, envContent)
      console.log('[OpenClaw] Config written:', envFile)
    }
  } catch {
    fs.writeFileSync(envFile, envContent)
  }
}

/**
 * Update OpenClaw config with fresh JWT for API auth
 */
export function updateOpenClawToken(jwt: string) {
  const dataDir = getDataDir()
  const envFile = path.join(dataDir, '.env')
  try {
    if (fs.existsSync(envFile)) {
      let content = fs.readFileSync(envFile, 'utf-8')
      content = content.replace(/OPENAI_API_KEY=.+/, `OPENAI_API_KEY=${jwt}`)
      fs.writeFileSync(envFile, content)
    }
  } catch (err) {
    console.error('[OpenClaw] Failed to update token:', err)
  }
}

export function startOpenClaw(): Promise<void> {
  return new Promise((resolve, reject) => {
    if (openClawProcess) {
      resolve()
      return
    }

    const clawDir = getOpenClawDir()
    const nodePath = getNodePath()
    const entryScript = path.join(clawDir, 'index.js')

    if (!fs.existsSync(entryScript)) {
      console.warn('[OpenClaw] Entry script not found, skipping:', entryScript)
      resolve()
      return
    }

    // Ensure config is ready
    ensureOpenClawConfig()

    const dataDir = getDataDir()

    openClawProcess = spawn(nodePath, [entryScript], {
      cwd: clawDir,
      env: {
        ...process.env,
        OPENCLAW_DATA_DIR: dataDir,
        NODE_ENV: 'production',
        PORT: String(OPENCLAW_PORT),
      },
      stdio: ['pipe', 'pipe', 'pipe'],
    })

    openClawProcess.stdout?.on('data', (data: Buffer) => {
      console.log('[OpenClaw]', data.toString().trim())
    })

    openClawProcess.stderr?.on('data', (data: Buffer) => {
      console.error('[OpenClaw Error]', data.toString().trim())
    })

    openClawProcess.on('error', (err) => {
      console.error('[OpenClaw] Failed to start:', err.message)
      openClawProcess = null
      reject(err)
    })

    openClawProcess.on('exit', (code) => {
      console.log('[OpenClaw] Exited with code:', code)
      openClawProcess = null
    })

    // Wait a bit for the server to start
    setTimeout(() => resolve(), 2000)
  })
}

export function stopOpenClaw(): void {
  if (openClawProcess) {
    openClawProcess.kill('SIGTERM')
    openClawProcess = null
    console.log('[OpenClaw] Stopped')
  }
}

export function restartOpenClaw(): Promise<void> {
  stopOpenClaw()
  return startOpenClaw()
}

export function isOpenClawRunning(): boolean {
  return openClawProcess !== null && !openClawProcess.killed
}

export function getOpenClawPort(): number {
  return OPENCLAW_PORT
}
